### ISSUE TITLE
consider pinned repos

### ISSUE THREAD

**Issue by tkphd** [usnistgov/awesome-nist#11]
Are the following repositories awesome?
- [x] https://github.com/usnistgov/800-63-3
  - Using GitHub for interactive public development of a standard is definitely awesome.
  - SP 800-63-3 has been published, and no longer solicits public input/commentary.
  - It might be better to free up this pin for a repo that web-surfers might be more interested in.
- [x] https://github.com/usnistgov/fipy
  - FiPy is awesome, and should remain pinned.
- [x] https://github.com/usnistgov/mobile-threat-catalogue
  - Of interest to anybody with a mobile phone. Should remain pinned.
- [x] https://github.com/usnistgov/applesec
  - [SP 800-179](https://csrc.nist.gov/publications/detail/sp/800-179/final) was published 12/2016, and is no longer open for public comment.
  - It might be better to free up this pin for a repo that web-surfers might be more interested in.
- [x] https://github.com/usnistgov/jsip
  - Looks active, and perhaps of interest. Should remain pinned.
- [x] https://github.com/usnistgov/trec_eval
  - This repo hasn't been updated since 2016. It should probably not remain pinned.

(If not, consider un-pinning from https://github.com/usnistgov)

**Comment by agmorey** [comment]
Today it's based soley on Stars.
![pinnedusnistgov](https://user-images.githubusercontent.com/5330387/41934628-32245abe-7955-11e8-9c6e-f103944e19ca.JPG)

**Comment by tkphd** [comment]
Sensible.

From the looks of it, [800-63-3](https://github.com/usnistgov/800-63-3) has been [published](https://pages.nist.gov/800-63-3/), which might mean that the public interaction period is over. Do the authors know it's pinned, and agree that it's still useful to advertise it? FWIW, it's cool that they did this using GitHub, and it'll probably get listed anyway, I'm just not sure if the majority of visitors to [usnistgov](https://github.com/usnistgov) still come looking for the raw material behind the Special Publication.

**Comment by tkphd** [comment]
Updated the original comment.

**Comment by tkphd** [comment]
@agmorey, @mnewrock, two of the pinned repos are finalized Special Publications, and one appears to be a dormant software project. Unpinning these would make room for OSCAL, MDCS, and ACVP, all of which are both active and awesome.

Most-starred is not a bad selection criterion, but there's room for judgment at the top.

**Comment by agmorey** [comment]
@tkphd, @mnewrock, @crhume - point taken, adjusted pin list.  I'd like to see the traffic statistics for all 760 repos sorted by most accessed, the statistics are available per repo in the insight tab, some of this might be available via the API.  Number of forks would be a good metric too, and a great report for impact across all NIST repos, also available per repo on the insights tab.
