### ISSUE TITLE
Request for Comments

### ISSUE THREAD

**Issue by tkphd** [usnistgov/awesome-nist#18]
Are the [criteria](https://github.com/usnistgov/awesome-nist/blob/master/.github/pull_request_template.md) sufficient to filter *awesome* from merely *good* repositories?

Do the [candidates](https://github.com/usnistgov/awesome-nist/issues?q=is%3Aopen+is%3Aissue) represent the best efforts of NIST coders?

Leave your thoughts and comments below!

**Comment by ranganathanm** [comment]
There is already a "curated list". It is the pinned set of repositories when you access https://github.com/usnistgov which uses the  number of stars as the criterion. Not sure why this exercise is relevant. Opensource is awesome because people who use it think it is is important - not because we (inside nist) think it is important.

**Comment by tkphd** [comment]
Thanks for the feedback, @ranganathanm. There can be only six pinned repositories, and the number of stars corresponds to the population of the associated community, not to the quality of the repository -- much like a [heatmap](https://xkcd.com/1138/).

The purpose of this exercise is to identify and showcase *good* repositories, regardless of current *involvement*, and create an easier way for the public to discover what we're up.

**Comment by HaroldHatchNIST** [comment]
If the criteria result in an improved repo and the list possibly helps to motivate someone, then I don't see any harm in it as long as the process is not too onerous for either the repo or awesome-list owner. I appreciate the extra work to put this together. Thank you

**Comment by wd15** [comment]
@ranganathanm, I agree that open source is self selecting and that the developers and users of the code are the best reviewers, however, a more formal review process can be helpful. For example,

 - I've been asked to review codes on a number of occasions and don't have a solid set of guidelines to help in that process.

 - One of the difficulties that I've had when developing codes is getting someone willing to give a review and an opinion on my work or even someone willing to review a pull request. In that sense, a formal process is helpful for developers that want outside review and can't currently get help.

 - It is not always clear as to what constitutes a satisfactory code release and your user base doesn't always give that sort of feedback assuming that you even have a user base.

Some other random thoughts.

 - Awesome-NIST should have solid review guidelines. Currently this seems to be the pull request template.

 - Awesome-NIST should have a really good README.md as an example based on https://github.com/noffle/art-of-readme.

 - Awesome-NIST should have a good number of volunteer reviewers (along with their preferred language, expertise, etc). How does one sign up to be a reviewer? That should be made clear in the README.md. 

 - Awesome-NIST could possible adopt some of the guidelines used for [JOSS](https://joss.theoj.org/about) especially the "Reviewer Guidelines". The JOSS guidelines are actually a little sparse.

 - Awesome-NIST could possible have some listings for current state of the art for linting, testing, documentation tools etc for a given language or community. For example, I found out that a choice for Python linting is [Black](https://github.com/ambv/black) instead of [Pylint](https://www.pylint.org/) recently. Where can I document that?

**Comment by tkphd** [comment]
Great feedback, @wd15, thank you. Currently, the README is used as the list (only), and the review process is hinted at in CONTRIBUTING.md and the PR template. I can take action to make this more clear:
- Add a concise statement of purpose to README.md, in the spirit of [noffle](https://github.com/noffle/art-of-readme)
- Add reviewer guidelines to CONTRIBUTING.md, launching off from [JOSS](https://joss.theoj.org/about#reviewer_guidelines)
- Start outlining what "awesome" means in a new AWESOME.md, which would also be a good place for tool recommendations (CI, linting, HTML proofing, ...)

**Comment by ranganathanm** [comment]
My thoughts:


  1.  I get nervous when I hear words like "formal review". It is very hard to get code reviewers.  Voulunteer reviewers would be a great plus. Requests for code review should also be voluntary. I ask my peers to look at the README.md before I open up my repository. I have not been successful in getting non-users to read my code at NIST. Projects tend to be small ( one or two contributors ). Outside of the contributors, it is hard to find people with enough interest in your code.
  2.  Criteria for what constitutes "satisfactory" may be hard to define outside of the obvious ( for example, NIST disclaimers, README.md being clear and concise  etc. ) . We can check out the obvious issues and recommend tools (findbugs, pep8 c-lint etc.) but clearly a reviewer can't judge functionality by merely looking at code.
  3.  If your user base thinks your code is satisfactory, then I would claim that it is satisfactory. We are mostly writing experimental software here after all.
  4.  I think there should be NIST pages that categorize code based on what the function of the code is. This would allow people to quickly find what they want.
  5.  There are certain things open source users look for such as automated test cases, examples and clear HOW-TO documentation. Projects that do a good job with such things have a better chance of success. In the end, success is the best measure of awesomeness.



________________________________

**Comment by tkphd** [comment]
Thanks for spelling out your reservations, @ranganathanm: it's much more useful to me than your first comment, and highlights some things the statement of purpose should clarify.

Experienced [FOSS](https://en.wikipedia.org/wiki/Free_and_open-source_software)ers know to look for certain things (README, examples, tests, CI), but new *developers* apparently do not: a huge number of repositories on usnistgov do not have a README or any documentation at all.  Such codes are technically open source, but add little of value because they are not maintainable: a new user (or the original developer, after a month's vacation) will not be able to troubleshoot the code.

Broadly speaking, `awesome-nist` is intended to be a [carrot](https://en.wikipedia.org/wiki/Carrot_and_stick) to publicly acknowledge good development practices. By showcasing these codes, *and* providing the criteria used to select them, this list will provide a reference for new developers to figure out what they need to include in a basically satisfactory repository, and what extra effort goes in to a truly great project.

Difficult or not, code reviews are an essential part of good software development. It can be difficult to build a sustainable pool of reviewers, but getting one person to review your code is as easy as asking a friend or colleague for a favor. Some may grumble, but peer review is as important for source code as it is for manuscripts.

Assessments for `awesome-nist` are not code reviews, but subjective judgments by advanced developers of whether or not the development practices represent the best practices for research software development. Agreeing on appropriate criteria is indeed difficult, but that doesn't mean we shouldn't try. The first iteration is listed in the [pull request template](https://github.com/usnistgov/awesome-nist/blob/master/.github/pull_request_template.md): @ranganathanm and @wd15, can you comment specifically on the checklist?

Thanks!

**Comment by wd15** [comment]
On Fri, May 11, 2018 at 9:12 PM, M. Ranganathan
<notifications@github.com> wrote:
>
> My thoughts:
>
>
> 1. I get nervous when I hear words like "formal review". It is very hard to get code reviewers. Voulunteer reviewers would be a great plus. Requests for code review should also be voluntary. I ask my peers to look at the README.md before I open up my repository. I have not been successful in getting non-users to read my code at NIST. Projects tend to be small ( one or two contributors ). Outside of the contributors, it is hard to find people with enough interest in your code.

I should have written "informal review" by volunteers. Totally agree though.

> 2. Criteria for what constitutes "satisfactory" may be hard to define outside of the obvious ( for example, NIST disclaimers, README.md being clear and concise etc. ) . We can check out the obvious issues and recommend tools (findbugs, pep8 c-lint etc.) but clearly a reviewer can't judge functionality by merely looking at code.

A reviewer can also checkout out the code and run a few examples. 9 /
10 times they will find a problem.

> 3. If your user base thinks your code is satisfactory, then I would claim that it is satisfactory. We are mostly writing experimental software here after all.

I think that there are a lot of codes that don't have much of a user
base. Maybe the developer just wants a code for themselves that's well
managed/curated. I would say that might constitute a large proportion
of the codes under consideration.

-- 
Daniel Wheeler

**Comment by reid-a** [comment]
The Journal of Open Source Software has reviewer criteria, which is possibly a useful additional benchmark. Scroll down to "Reviewer Guidelines" on the ["about" page.](https://joss.theoj.org/about).

This isn't an exact match for what we want, the JOSS is also interested in novel applications, but they've clearly thought about what makes open-source software accessible and useful. The overlap with the candidate list is high, so this suggests we're on the right track.

**Comment by ranganathanm** [comment]
I looked at the checklist. The basic checklist is quite achievable. The bonus checklist is harder ( as one would expect ).


I would add the requirement to have automated style checking and static code checking when possible as part of the build process in the "bonus list:"


(Incidentally I signed up for travis-cI for one of my private repositories but it complains about not being able to charge my credit card -- which is a good thing 😊. Are these tools available to all NIST users for private repositories?)



________________________________

**Comment by tkphd** [comment]
@ranganathanm no, if you want to use Travis-CI with a private repo, you'll have to pay for it. Or, open the repo to the public.

**Comment by tkphd** [comment]
Style checking, static code analysis, and linting are all good suggestions, thanks.

**Comment by ranganathanm** [comment]
I wonder if it would be possible for NIST to pay for travis or jenkins licenses, like they do for private github repos,  so these can be run on private repositories prior to opening them up to the public.

________________________________

**Comment by tkphd** [comment]
Possible, but discouraged. If a repo must be kept private, host it on GitLab instead of GitHub, and use the GitLab CI. Ask the [GitLab list](https://groups.google.com/a/list.nist.gov/forum/#!forum/gitlab) (NIST credentials required) for assistance.

If a repo is for public consumption, why should it ever be private? Provided, of course, that early-development code comes with an appropriate disclaimer.

**Comment by ranganathanm** [comment]
One good reasons for private repo:


I want to collaborate with non-NIST people. For example I want to have people from industry review and comment on my work before opening it up to a wider audience.


A second reason:


I have some students who finish their stay at NIST and want to keep working on joint work but it is not "ready for prime time".





________________________________

**Comment by tkphd** [comment]
For the first one, external coders can collaborate without having write-access: use a [fork & request workflow](https://gist.github.com/Chaser324/ce0505fbed06b947d962), and allow only NIST members to merge pull requests into the usnistgov repository. Everyone else should use a fork on their own account (personal or organization). This would comply with the [terms of use](https://inet.nist.gov/odi/github).

If the repository contains proprietary information, it should be hosted on the GitLab service (NIST hardware on campus), not on GitHub. If a [CRADA](https://www.nist.gov/tpo/crada) is in place, and the code is considered proprietary, then a private repository on GitHub is appropriate. But, again, give serious consideration as to whether such information should really reside on commercial servers (GitHub or Travis).

For the second one, "not ready for prime time" is precisely the meaning of a sub-1.0 version number. If the student, or their advisor, feels strongly that the repo should be private, then it should be moved off of usnistgov and onto their university or research group's IT resources.

**Comment by ranganathanm** [comment]
I am not referring to proprietary information here nor am I referring to write access. Consider the following use case:


  1.  A standard is being evolved and NIST is implementing a reference implementation.
  2.  NIST members (with R/W access) want to share the reference implementation with the authors of the specification prior to it being finalized.
  3.  NIST members do not want to release code to the public prior to the specification being finalized.


One can restrict collaborators to read-only access for review purposes.  It is no different than sending a paper out for review to a non-NIST collaborator and asking that the paper not be re-circulated prior to publication. There is no intention of proprietary code here.



________________________________

**Comment by tkphd** [comment]
I'll concede that such a scenario *may* warrant a private repository, if the evolving standard is being written behind closed doors and there's good reason to withhold it from public scrutiny. I'm sure that similar scenarios with tight constraints exist, and warrant privacy as well.

This has gone a little off-topic, but I appreciate the dialogue. I should note that I'm a GitHub user, not a usnistgov admin, so my opinions should not be considered *writ*.

**Comment by ranganathanm** [comment]
To put it back on track, I  think you'll agree:


It is difficult to get reviewers to review your work for functional content (I am not referring to README or license or the other things we've been talking about). Te most interested reviewers of your work would be people inside and outside NIST who have an interest in collaborating or using your work (such as the use case below).  The other things mentioned in this thread are, in many cases, possible to achieve using build automation and automatic style checking tools.


Given that outside collaboration is an essential part of what we do and there is (at least one) use case for private repositories and given that collaborators and users are also the best testers and reviewers for our work, perhaps NIST can pay for some Travis CL or Jenkens licenses so build and test automation can be applied to private repos as well. Perhaps that is is not possible but one can hope.


I think it would be a great project to publish guidelines and guidance (not requirements but just guidance) for NIST developers unfamiliar with such tools to bring people up to speed on how to use such tools and incorporate them into their builds.


Incidentally, there are a few sites that rate public repositories on the basis of how well your code is commented, how long it takes for pull requests to be attended to and so forth. People tend to rely on these things for the "warm fuzzy" before intellectually investing in your code.


Thanks for the discussion.


________________________________

**Comment by tkphd** [comment]
Yes, I agree: automated services evaluate code for the same essential criteria we're considering for "awesome", and the "warm fuzzy" of green badges on a  repo encourages colleagues and the public to take a closer look. This is, in fact, a motivation for starting `awesome-nist`: there's no easy way to discover NIST repositories, beyond the pinned repo list or by sifting through the list of everything. By calling out codes that are already doing the right things, we can draw some attention (and eyeballs) to them and help foster communities that may be nascent or dormant. It's just another venue for advertising our open-source efforts, in a friendly, self-governing framework.
