### ISSUE TITLE
consider chebtools

### ISSUE THREAD

**Issue by ianhbell** [usnistgov/awesome-nist#20]
I opened a PR for this, but I didn't understand how things were supposed to work (oops).  Here it is: https://github.com/usnistgov/awesome-nist/pull/19

**Comment by tkphd** [comment]
https://github.com/usnistgov/chebtools

**Comment by tkphd** [comment]
The workflow was needlessly complicated, it's better now: submitting a PR directly was the right way to go. Thanks!
